spring:
  profiles:
    active: dev
  application:
    name: incede-customer-status-service

  datasource:
    url: jdbc:postgresql://localhost:5432/incede_masterservice_db
    username: postgres
    password: boot
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: MASTER_DATA  # Specify the schema
        format_sql: true
        jdbc:
          batch_size: 30
          order_inserts: true
          order_updates: true
        lob:
          non_contextual_creation: true
        generate_statistics: false
      open-in-view: false

server:
  port: 8080
